// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGIKpmRXYluK0ishJVj8vq-DY2VsVaFuM',
    appId: '1:597724230359:web:f07a7f82c25048831c3692',
    messagingSenderId: '597724230359',
    projectId: 'uanmgsakuku',
    authDomain: 'uanmgsakuku.firebaseapp.com',
    storageBucket: 'uanmgsakuku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcvNoIrCmgupr9WtRei2YtREwrgzFeF1k',
    appId: '1:597724230359:android:b7f6616394e11b711c3692',
    messagingSenderId: '597724230359',
    projectId: 'uanmgsakuku',
    storageBucket: 'uanmgsakuku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5ExZKTAOoYVNBhM0Re2O9MB5hvVcRJE',
    appId: '1:597724230359:ios:b09c45217693fdad1c3692',
    messagingSenderId: '597724230359',
    projectId: 'uanmgsakuku',
    storageBucket: 'uanmgsakuku.firebasestorage.app',
    iosBundleId: 'com.example.uangsakuku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ5ExZKTAOoYVNBhM0Re2O9MB5hvVcRJE',
    appId: '1:597724230359:ios:b09c45217693fdad1c3692',
    messagingSenderId: '597724230359',
    projectId: 'uanmgsakuku',
    storageBucket: 'uanmgsakuku.firebasestorage.app',
    iosBundleId: 'com.example.uangsakuku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGIKpmRXYluK0ishJVj8vq-DY2VsVaFuM',
    appId: '1:597724230359:web:c81f334fd2ba7fe81c3692',
    messagingSenderId: '597724230359',
    projectId: 'uanmgsakuku',
    authDomain: 'uanmgsakuku.firebaseapp.com',
    storageBucket: 'uanmgsakuku.firebasestorage.app',
  );
}
